#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           intakeMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| MANINDER |+++++++++++++++++++++++++++++++++++++++++++++++

Task Description: Basic template for a VEX Change Up robot. Includes basic driving, intake control, and lift mechanism control.

                      Controls:
                      - Joystick channel 3: Left motor (forward/backward)
                      - Joystick channel 2: Right motor (forward/backward)
                      - Button 6U: Lift up
                      - Button 6D: Lift down
                      - Button 5U: Intake forward
                      - Button 5D: Intake backward

--------------------------------------------------------------------------------------------------------*/

task main()
{
    while(true)
    {
        // Driving control
        motor[leftMotor] = vexRT[Ch3];  // Left joystick vertical axis controls left motor
        motor[rightMotor] = vexRT[Ch2]; // Right joystick vertical axis controls right motor

        // Lift control
        if(vexRT[Btn6U] == 1) {
            motor[liftMotor] = 127; // Lift up when button 6U is pressed
        } else if(vexRT[Btn6D] == 1) {
            motor[liftMotor] = -127; // Lift down when button 6D is pressed
        } else {
            motor[liftMotor] = 0;   // Stop lift when no button is pressed
        }

        // Intake control
        if(vexRT[Btn5U] == 1) {
            motor[intakeMotor] = 127;   // Intake forward when button 5U is pressed
        } else if(vexRT[Btn5D] == 1) {
            motor[intakeMotor] = -127;  // Intake backward when button 5D is pressed
        } else {
            motor[intakeMotor] = 0;     // Stop intake when no button is pressed
        }
    }
}
