#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           trapServo,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| MANINDER |+++++++++++++++++++++++++++++++++++++++++++++++

		Task Description: Detect black balls using a light sensor and use an encoder to measure distance. 
		Open a servo mechanism to trap the black balls when detected.


																						-BUTTONS/AXISES-

																				1|2 AXIS  --- Right motor
																				 3|4 AXIS --- Left motor

*/

void trapBall()
{
	// Open the trap
	motor[trapServo] = 127;  // Set servo to open position
	wait1Msec(1000);         // Wait for 1 second to simulate trapping mechanism
	motor[trapServo] = -127; // Reset servo to initial position
	wait1Msec(1000);         // Wait for 1 second to ensure the servo returns
	motor[trapServo] = 0;    // Stop the servo
}

task main()
{
	int lightThreshold = 2000;  // Adjust this value based on your light sensor readings

	while(true){
		// Drive control
		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch2];

		// Check the light sensor value
		if(SensorValue[lightSensor] < lightThreshold)
		{
			trapBall();  // Call the trapBall function when a black ball is detected
		}
	}
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
