#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           launcherMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intakeMotor,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| MANINDER |+++++++++++++++++++++++++++++++++++++++++++++++

Task Description: Basic template for a VEX Spin Up robot. Includes basic driving, intake control, and launching mechanism.

                      Controls:
                      - Joystick channel 3: Left motor (forward/backward)
                      - Joystick channel 2: Right motor (forward/backward)
                      - Button 6U: Launch discs
                      - Button 5U: Intake discs

--------------------------------------------------------------------------------------------------------*/

task main()
{
    while(true)
    {
        // Driving control
        motor[leftMotor] = vexRT[Ch3];  // Left joystick vertical axis controls left motor
        motor[rightMotor] = vexRT[Ch2]; // Right joystick vertical axis controls right motor

        // Launcher control
        if(vexRT[Btn6U] == 1) {
            motor[launcherMotor] = 127; // Launch discs when button 6U is pressed
        } else {
            motor[launcherMotor] = 0;   // Stop launching when button 6U is released
        }

        // Intake control
        if(vexRT[Btn5U] == 1) {
            motor[intakeMotor] = 127;   // Intake discs when button 5U is pressed
        } else {
            motor[intakeMotor] = 0;     // Stop intake when button 5U is released
        }
    }
}
