#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           armServo,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| MANINDER |+++++++++++++++++++++++++++++++++++++++++++++++

		Task Description: Make the two motors at the bottom move. Make two servos make arm move and claw open/close


																						-BUTTONS/AXISES-

																				1|2 AXIS  --- Right motor
																				 3|4 AXIS --- Left motor
																					 6U --- Arm Moves Up
																					6D --- Arm Moves Down
																					  5U --- Claw Opens
																						5D --- Claw Closes


*/


task main()
{
	while(true){
  	motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch2];
		//motor[armServo] = vexRT[Btn6U];
		//motor[clawServo] = vexRT[Btn5U];
    //Arm Control
    while(vexRT[Btn6U] == 1)
    {
      motor[armServo] = 127;
    }
    while(vexRT[Btn6D] == 1)
    {
      motor[armServo] = -90;
    }
    /*
    else
    {
      motor[armServo] = 0;
    }
    */

    //Claw Control

  }
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
