#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           kickServo,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| MANINDER |+++++++++++++++++++++++++++++++++++++++++++++++

		Task Description: Make the two motors at the bottom move. Use a servo to kick the ball.


																						-BUTTONS/AXISES-

																				1|2 AXIS  --- Right motor
																				 3|4 AXIS --- Left motor
																					 6U --- Kick the ball


*/

task main()
{
	while(true){
		// Drive control
  		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch2];

		// Kick control
		if(vexRT[Btn6U] == 1)
		{
			motor[kickServo] = 127;  // Set servo to kick position
			wait1Msec(500);          // Wait for 0.5 second to simulate the kick
			motor[kickServo] = -127; // Reset servo to initial position
			wait1Msec(500);          // Wait for 0.5 second to ensure the servo returns
		}
		else
		{
			motor[kickServo] = 0;    // Ensure servo is not moving if button is not pressed
		}
	}
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
